export const houseTypes = [
  {
    type: "Basic Type",
    image1: "/images/basic-1.png",
    image2: "/images/basic-2.png",
    bed: "2",
    bath: "3",
    car: "2",
    floor1: [
      "Carport",
      "Living Room",
      "Dining Room",
      "Kitchen",
      "Bathroom 1",
      "Terrace",
      "Garden",
    ],
    floor2: [
      "Master Bedroom",
      "Master Bathroom",
      "Bathroom 2",
      "Corridor",
      "Bedroom 2",
      "Balcony",
    ],
  },
  {
    type: "Dynasty Type",
    image1: "/images/dynasty-1.png",
    image2: "/images/dynasty-2.png",
    bed: "4",
    bath: "3",
    car: "2",
    floor1: [
      "Carport",
      "Living Room",
      "Dining Room",
      "Kitchen",
      "Bathroom 1",
      "Bedroom 1",
      "Terrace",
      "Garden",
    ],
    floor2: [
      "Master Bedroom",
      "Master Bathroom",
      "Bathroom 2",
      "Corridor",
      "Bedroom 3",
      "Bedroom 4",
      "Balcony",
    ],
  },
  {
    type: "Executive Type",
    image1: "/images/executive-1.png",
    image2: "/images/executive-2.png",
    bed: "3",
    bath: "3",
    car: "2",
    floor1: [
      "Carport",
      "Living Room",
      "Dining Room",
      "Kitchen",
      "Bathroom 1",
      "Multifunction Room",
      "Terrace",
      "Garden",
    ],
    floor2: [
      "Master Bedroom",
      "Master Bathroom",
      "Bathroom 2",
      "Corridor",
      "Bedroom 1",
      "Bedroom 2",
      "Balcony",
    ],
  },
  {
    type: "Luxury Type",
    image1: "/images/luxury-1.png",
    image2: "/images/luxury-2.png",
    bed: "3",
    bath: "3",
    car: "2",
    floor1: [
      "Carport",
      "Living Room",
      "Dining Room",
      "Kitchen",
      "Bathroom 1",
      "Terrace",
      "Service Bedroom",
      "Service Bedroom",
      "Service Bathroom",
      "Service Area",
    ],
    floor2: [
      "Master Bedroom",
      "Master Bathroom",
      "Bathroom 2",
      "Corridor",
      "Bedroom 1",
      "Bedroom 2",
      "Balcony",
    ],
  },
];
